project_id = "vzrdmjbcbhhyutppuxcf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://vzrdmjbcbhhyutppuxcf.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.send-email]
verify_jwt = false

[functions.share-opportunity]
verify_jwt = false

[functions.track-opportunity-view]
verify_jwt = false

[functions.extract-property-data]
verify_jwt = false

[functions.rate-limit-submissions]
verify_jwt = false

[functions.send-signature]
verify_jwt = false

[functions.signature-webhook]
verify_jwt = false