// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzrdmjbcbhhyutppuxcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6cmRtamJjYmhoeXV0cHB1eGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTgwMDEsImV4cCI6MjA2ODUzNDAwMX0.4BkwV6kp8Jmodm13VezaGYI6todQ4BC2G_hTH8y5SwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});